name: pandaboard-kernel
version: 3.13
summary: A OMAP4 kernel built from source
description: This is the reference kernel from Ubuntu
type: kernel
grade: devel
architectures: [ armhf ]

parts:
    kernel:
        plugin: kernel
        source: git://kernel.ubuntu.com/ubuntu/ubuntu-trusty.git
        source-depth: 1
        source-branch: master
        source-type: git
        kdefconfig: [omap2plus_defconfig]
        kconfigs:
            - CONFIG_LOCALVERSION="-panda"
            - CONFIG_DEBUG_INFO=n
            - CONFIG_NAMESPACES=y
            - CONFIG_CGROUPS=y
            - CONFIG_AUTOFS4_FS=m
            - CONFIG_SQUASHFS=m
            - CONFIG_SQUASHFS_XZ=y
            - CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
            - CONFIG_MAC80211_LEDS=y
            - CONFIG_RFKILL_LEDS=y
            - CONFIG_LEDS_TRIGGERS=y
        kernel-initrd-modules:
            - squashfs
        kernel-image-target: zImage
        kernel-device-trees:
            - omap4-panda
        build-packages: [bc, kmod, cpio]
